import {useEffect,useRef,useState} from 'react';
import {Activity,ArrowRight,ArrowUpRight,BookOpen,Check,ChevronLeft,ChevronRight,Download,FlaskConical,LayoutDashboard,Menu,Presentation,Radio,ShieldCheck,Users,Wind,X} from 'lucide-react';
import {Card,LineChart,MetricCard,PageTitle,SiteMap,SourceLink,Tag,Transport,usePlayback} from './components';
import {clock,fallbackJson,getJson,loadScenario,number,recordedSnapshot,strategies,strategyNames} from './data';
import type {Evidence,Episode,ReplayIndex,Scenario,ScenarioIndex,Site,Snapshot,Strategy} from './data';

const pages=[['overview','Overview',LayoutDashboard],['replay','AI replay',Activity],['experiment','Site experiment',Wind],['results','Evidence & results',FlaskConical],['system','Round 2 design',Radio],['team','Our team',Users],['present','Present',Presentation]] as const;
const colours:Record<Strategy,string>={no_control:'#c1aaa0',continuous:'#7ca4d8',reactive:'#e7b76e',predictive:'#81dfb6'};
const modelNames:Record<string,string>={persistence:'Persistence',trailing_mean:'Trailing mean',selected_model:'Trained model'};
function go(page:string){location.hash=page;}
function Banner({children,tone=''}:{children:React.ReactNode;tone?:string}){return <div className={`banner ${tone}`}><ShieldCheck size={18}/><div>{children}</div></div>;}
function download(value:unknown,name:string){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function ResultTable({scenario}:{scenario:Scenario}){return <div className="table-wrap"><table><thead><tr><th>Strategy</th><th>Water · L</th><th>Mean max PM10</th><th>Peak PM10</th><th>Above setting · s</th><th>Switches</th></tr></thead><tbody>{strategies.map(s=>{const m=scenario.runs[s].metrics;return <tr key={s} className={s==='predictive'?'selected-row':''}><td><span className="legend-dot" style={{background:colours[s]}}/>{strategyNames[s]}</td><td>{number(m.water_litres,3)}</td><td>{number(m.mean_max_boundary_pm10_ug_m3)}</td><td>{number(m.peak_boundary_pm10_ug_m3)}</td><td>{m.exceedance_seconds}</td><td>{m.zone_switches}</td></tr>;})}</tbody></table></div>;}

function Overview({evidence,site}:{evidence:Evidence;site:Site}){return <>
  <div className="hero card"><div className="hero-copy"><Tag>Round 1 · working software prototype</Tag><h1>Forecast dust.<br/><em>Control the edge.</em></h1><p>DustTwin connects a trained dust forecast with a proposed, zone-based misting system. Explore the measured AI replay, then test control decisions in our site simulation.</p><div className="button-row"><button className="button primary" onClick={()=>go('replay')}>See the AI working <ArrowRight size={17}/></button><button className="button" onClick={()=>go('experiment')}>Explore the site</button></div><div className="hero-foot"><span><Check size={14}/> Real recorded data</span><span><Check size={14}/> Works offline after setup</span></div></div><div className="hero-map"><span className="small-label">PROPOSED SITE CONTROL</span><SiteMap illustration/><span className="map-caption">An illustrative layout. Physical hardware is planned for Round 2.</span></div></div>
  <div className="metrics four"><MetricCard label="Forecast horizon" value="30" unit="s" note="One monitor endpoint from 120 seconds of past measurements."/><MetricCard label="Audited construction records" value="12" note="Laboratory OPC-N3 recordings · one instrument and setup."/><MetricCard label="Unseen test MAE" value={number(evidence.test.models.selected_model.mae_ug_m3)} unit="µg/m³" note={`Trailing mean is better on MAE: ${number(evidence.test.models.trailing_mean.mae_ug_m3)} µg/m³.`}/><MetricCard label="Fair control comparison" value="4 × 5" note="Four strategies, five cases, the same environment and actuators."/></div>
  <div className="section-heading"><div><span className="eyebrow">THE IDEA</span><h2>Make the next action visible.</h2></div><span className="muted">From measurements to a reviewable decision</span></div>
  <div className="grid three"><Card><span className="step">01 / MEASURE</span><h3>A construction problem</h3><p>Dust from construction sites is part of Bangladesh’s air-quality challenge. Our proposal focuses on monitoring a site and directing misting toward exposed boundaries.</p><SourceLink href={site.problem_source.url}>World Bank · local context</SourceLink></Card><Card><span className="step">02 / FORECAST</span><h3>A real learned model</h3><p>A small boosting model learns PM10 patterns from past readings. Every replay shows its output beside two simple baselines and reveals the actual measurement when time catches up.</p><button className="text-button" onClick={()=>go('replay')}>Inspect a prediction <ArrowUpRight size={15}/></button></Card><Card><span className="step">03 / ACT</span><h3>A proposed control loop</h3><p>The site experiment combines that model with assumed transport and mist response. Water, exposure and switching are calculated from saved traces for every strategy.</p><button className="text-button" onClick={()=>go('experiment')}>Compare the tradeoffs <ArrowUpRight size={15}/></button></Card></div>
  <Banner>Measured forecasting and simulated site control are separate evidence. Outdoor boundary accuracy and physical dust suppression still require a calibrated pilot.</Banner>
</>;}

function Replay({index}:{index:ReplayIndex}){
  const [id,setId]=useState('lab_e4_drill90');const episode=index.episodes.find(e=>e.episode_id===id)!;
  const player=usePlayback(episode.suggested_start_second,episode.first_issue_second,episode.last_issue_second);
  const [snapshot,setSnapshot]=useState<Snapshot|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true);
  useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');setSnapshot(null);(async()=>{try{let data:Snapshot;try{data=await getJson<Snapshot>(`/v1/replay/${id}?second=${player.second}`,controller.signal);}catch(e){if(controller.signal.aborted)throw e;data=await recordedSnapshot(index,episode,player.second,controller.signal);}if(!controller.signal.aborted)setSnapshot(data);}catch(e){if(!controller.signal.aborted)setError(String(e));}finally{if(!controller.signal.aborted)setLoading(false);}})();return()=>controller.abort();},[id,player.second,index]);
  function changeEpisode(e:Episode){player.setPlaying(false);player.setSecond(e.suggested_start_second);setId(e.episode_id);}
  const currentSnapshot=snapshot?.clock_second===player.second&&snapshot.episode_id===id?snapshot:null;
  const f=currentSnapshot?.forecast;
  return <><PageTitle eyebrow="MEASURED LABORATORY DATA" title="Watch the AI make a forecast." description="Only past readings enter the model. The next recorded measurement is revealed when the replay clock reaches it." action={<Tag tone={f?.mode==='live_inference'?'mint':'sand'}>{f?.mode==='live_inference'?'Live local inference':'Saved inference replay'}</Tag>}/>
    <Card><div className="card-toolbar"><label className="field inline">Recording<select aria-label="Recording" value={id} onChange={e=>changeEpisode(index.episodes.find(x=>x.episode_id===e.target.value)!)}>{index.episodes.map(e=><option key={e.episode_id} value={e.episode_id}>{e.label} · {e.partition}</option>)}</select></label><span className="muted">OPC-N3 · raw PM10 · 1-second causal grid</span></div><Transport player={player} label="Measured replay time"/></Card>
    {loading&&<div className="loading" role="status">Loading forecast at {clock(player.second)}…</div>}{error&&<Banner tone="sand">{error}</Banner>}
    {currentSnapshot&&snapshot&&f&&<><div className="metrics four"><MetricCard label={`Observed now · ${clock(player.second)}`} value={number(f.current_pm10_ug_m3)} unit="µg/m³" note="Latest available past observation."/><div data-testid="model-prediction"><MetricCard label={`AI endpoint · ${clock(f.target_time_seconds)}`} value={number(f.predicted_pm10_ug_m3)} unit="µg/m³" note="Trained model · 30 seconds ahead." tone="accent"/></div><MetricCard label="Persistence endpoint" value={number(f.baselines.persistence_pm10_ug_m3)} unit="µg/m³" note="Assumes the current reading continues."/><MetricCard label="Trailing mean endpoint" value={number(f.baselines.trailing_mean_pm10_ug_m3)} unit="µg/m³" note="Mean of the preceding 30 snapshots."/></div>
    <Card><div className="section-heading"><h3>Past observations → future endpoints</h3><span className="small-label">FUTURE ACTUAL IS HIDDEN</span></div><LineChart series={[{name:'Recorded past',color:'#aebcc2',points:snapshot.past_observations.map(p=>({x:p.time_seconds,y:p.pm10_ug_m3}))},{name:'Trained forecast',color:'#81dfb6',points:[{x:f.target_time_seconds,y:f.predicted_pm10_ug_m3}]},{name:'Persistence',color:'#7ca4d8',points:[{x:f.target_time_seconds,y:f.baselines.persistence_pm10_ug_m3}]},{name:'Trailing mean',color:'#e7b76e',points:[{x:f.target_time_seconds,y:f.baselines.trailing_mean_pm10_ug_m3}]}]}/></Card>
    <div className="grid two"><Card><div className="small-label">WHEN TIME CATCHES UP</div><h3>Compare a matured forecast</h3>{snapshot.matured_forecast?<div data-testid="matured-result"><p>Issued at <strong>{clock(snapshot.matured_forecast.issue_time_seconds)}</strong> for <strong>{clock(snapshot.matured_forecast.target_time_seconds)}</strong>.</p><div className="mini-metrics"><div><span>Earlier forecast</span><strong>{number(snapshot.matured_forecast.predicted_pm10_ug_m3)}<small> µg/m³</small></strong></div><div><span>Recorded actual</span><strong>{number(snapshot.matured_forecast.actual_pm10_ug_m3)}<small> µg/m³</small></strong></div></div></div>:<p data-testid="matured-waiting">Advance 30 seconds from the first eligible forecast to reveal its actual target.</p>}<p className="caption">The issue and target clocks belong to this recording. No invented calendar date or independent field result.</p></Card><Card><div className="small-label">WHAT THE MODEL KNOWS</div><h3>121 past snapshots, 16 features</h3><p>PM10 lags, trailing means, variation and slopes. Wind, drilling labels and future activity are excluded from learned inputs.</p><p>A single endpoint does not provide a crossing time or calibrated confidence. The replay has no exact ETA.</p><details><summary>Inspect the inference input and artifact</summary><dl className="key-values"><dt>Mode</dt><dd>{f.mode}</dd><dt>Issue / target seconds</dt><dd>{f.issue_time_seconds} / {f.target_time_seconds}</dd><dt>Model</dt><dd className="mono">{f.model_id}</dd><dt>Artifact SHA-256</dt><dd className="mono break">{f.artifact_sha256}</dd>{f.inference_milliseconds!==undefined&&<><dt>Inference time</dt><dd>{number(f.inference_milliseconds,3)} ms</dd></>}{f.input_quality&&<><dt>Oldest input age</dt><dd>{number(f.input_quality.maximum_observation_age_seconds,3)} s · maximum 1.5 s</dd></>}</dl>{f.features?<div className="feature-list">{Object.entries(f.features).map(([key,value])=><div key={key}><span>{key}</span><span>{number(value,3)}</span></div>)}</div>:<p>Previously computed output; no model execution or feature recomputation in this browser.</p>}<button className="button compact" onClick={()=>download(snapshot,`dusttwin-${id}-${player.second}.json`)}><Download size={15}/>Download this snapshot</button></details></Card></div>
    <Banner tone="sand">The learned model beats persistence on test MAE, but loses to the trailing mean. Abrupt onsets and peaks are weaknesses. <button className="text-button" onClick={()=>go('results')}>Read the complete results <ArrowRight size={14}/></button></Banner></>}
    <div className="attribution"><p>{index.attribution}</p><SourceLink href={index.source_url}>Dataset and reuse terms</SourceLink></div>
  </>;
}

function Experiment({index,live}:{index:ScenarioIndex;live:boolean}){
  const [id,setId]=useState('east'),[strategy,setStrategy]=useState<Strategy>('predictive'),[scenario,setScenario]=useState<Scenario|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const player=usePlayback(0,0,480),generation=useRef(0);
  const [draft,setDraft]=useState({source_scale:1,wind_from_degrees:270,wind_speed_metres_second:3,flow_litres_minute_per_zone:.5,mist_source_fraction_removed:.65}),[custom,setCustom]=useState(false);
  useEffect(()=>{const token=++generation.current;setBusy(true);setError('');setScenario(null);setCustom(false);loadScenario(id,index).then(s=>{if(token!==generation.current)return;setScenario(s);setDraft({source_scale:1,wind_from_degrees:s.case.wind_from_degrees,wind_speed_metres_second:s.parameters.wind_speed_metres_second,flow_litres_minute_per_zone:s.parameters.flow_litres_minute_per_zone,mist_source_fraction_removed:s.parameters.mist_source_fraction_removed});}).catch(e=>{if(token===generation.current)setError(String(e));}).finally(()=>{if(token===generation.current)setBusy(false);});return()=>{generation.current++;};},[id,index]);
  async function apply(){const token=++generation.current;setBusy(true);setError('');player.setPlaying(false);try{const response=await fetch('/v1/simulate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({scenario_id:id,...draft})});if(!response.ok)throw new Error(`Could not apply assumptions (${response.status}). Saved evidence is still available.`);const next:Scenario=await response.json();if(token===generation.current){setScenario(next);setCustom(true);player.setSecond(0);}}catch(e){if(token===generation.current)setError(String(e));}finally{if(token===generation.current)setBusy(false);}}
  const point=scenario?.runs[strategy].trace[player.second];const max=point?Math.max(...point.pm10_ug_m3):0;
  return <><PageTitle eyebrow="ILLUSTRATIVE SITE SIMULATION" title="Explore the control decision." description="One source, weather timeline and actuator model. Change the strategy to see the same moment through a different controller." action={<Tag tone="sand">Simulated · no physical validation</Tag>}/>
    <Banner>Boundary transport and mist response are assumptions. The trained monitor model is applied to a synthetic source proxy; that domain transfer has not been validated.</Banner>
    <Card><div className="card-toolbar"><label className="field inline">Scenario<select aria-label="Scenario" disabled={busy} value={id} onChange={e=>{player.reset();setId(e.target.value);}}>{index.scenarios.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><div className="segmented" aria-label="Control strategies">{strategies.map(s=><button key={s} className={strategy===s?'active':''} aria-pressed={strategy===s} onClick={()=>setStrategy(s)}>{strategyNames[s]}</button>)}</div></div><Transport player={player} label="Site replay time"/></Card>
    {error&&<Banner tone="sand">{error}</Banner>}{busy&&<div className="loading" role="status">Running the same environment for all four strategies…</div>}
    {scenario&&point&&<><div className="grid experiment-grid"><Card className="map-card"><div className="section-heading"><h3>{strategyNames[strategy]} · {clock(player.second)}</h3><Tag tone={point.data_available?'mint':'sand'}>{point.data_available?'Simulated sensors available':'Sensor interruption'}</Tag></div><SiteMap windFrom={point.wind_from_degrees??scenario.case.wind_from_degrees} concentrations={point.pm10_ug_m3} active={point.commands} risk={point.forecast?.risk_zones??[]}/>{!point.data_available&&<p className="caption">Displayed concentrations are simulation truth for inspection. The controller cannot observe them; it requests all zones under the same actuator limits.</p>}</Card><div className="stack"><MetricCard label="Water used so far" value={number(point.water_litres,3)} unit="L" note={`${number(scenario.parameters.flow_litres_minute_per_zone,2)} L/min per commanded zone × actual on time.`} tone="accent"/><MetricCard label="Current maximum boundary" value={number(max)} unit="µg/m³" note={`Demo trigger ${scenario.parameters.boundary_setting_ug_m3} · assumed background ${scenario.parameters.ambient_pm10_ug_m3}.`}/><Card><span className="small-label">SOURCE PROXY · NOT AN EMISSION RATE</span><div className="mini-value">{point.source_proxy_pm10_ug_m3===null?'Unavailable':`${number(point.source_proxy_pm10_ug_m3)} µg/m³`}</div><p className="caption">Synthetic observation at this clock.</p></Card></div></div>
    <Card><div className="section-heading"><h3>Zone decisions</h3><span className="muted">A north · B east · C south · D west</span></div><div className="zones">{['A','B','C','D'].map((zone,i)=>{const crossing=point.forecast?.crossings?.[i];return <div className="zone" key={zone}><div><strong>Zone {zone}</strong><Tag tone={point.commands[i]?'mint':'neutral'}>{point.commands[i]?'Command on':'Command off'}</Tag></div><span>{number(point.pm10_ug_m3[i])} µg/m³</span><p>{crossing?crossing.status==='already_exceeded'?'Already above setting at issue':crossing.eta_seconds!==null?`Assumed crossing in ${crossing.eta_seconds} s from issue`:'No crossing in predicted horizon':strategy==='predictive'?'Forecast unavailable / starting':'This strategy uses no forecast'}</p><small>{point.effective_misting?.[i]?'Mist effect active':'Mist effect inactive'}</small></div>;})}</div>{point.forecast&&<p className="caption">Decision issued at {clock(point.forecast.issue_second)}. {point.forecast.forecast_status.replaceAll('_',' ')}. ETA uses a linear source path to the learned endpoint, held-current wind and untreated boundary rollout.</p>}</Card>
    <Card><h3>Same clock, all four strategies</h3><LineChart setting={scenario.parameters.boundary_setting_ug_m3} xMax={480} series={strategies.map(s=>({name:strategyNames[s],color:colours[s],points:scenario.runs[s].trace.slice(0,player.second+1).map(p=>({x:p.second,y:Math.max(...p.pm10_ug_m3)}))}))}/></Card>
    <Card><div className="section-heading"><div><h3>Complete eight-minute comparison</h3><p className="caption">{custom?'Custom assumptions':'Saved frozen scenario'} · PM10 in µg/m³ · means use the maximum of the four boundaries each second.</p></div><button className="button compact" onClick={()=>download(scenario,`dusttwin-${id}-${custom?'custom':'saved'}.json`)}><Download size={15}/>Export traces</button></div><ResultTable scenario={scenario}/></Card>
    <Card><details><summary>Change the assumptions</summary><p>These controls rerun all four strategies with the same new settings. They are hypothetical choices, not calibrated hardware performance.</p><div className="assumptions">{([['source_scale','Source multiplier',.25,2,.05],['wind_from_degrees','Wind from · degrees',0,359,1],['wind_speed_metres_second','Wind speed · m/s',.5,12,.5],['flow_litres_minute_per_zone','Flow per zone · L/min',.1,2,.05],['mist_source_fraction_removed','Incoming source fraction removed',0,.95,.05]] as const).map(([key,label,min,max,step])=><label className="field" key={key}>{label}<input type="number" aria-label={label} min={min} max={max} step={step} value={draft[key]} onChange={e=>setDraft({...draft,[key]:Number(e.target.value)})}/></label>)}</div><button className="button primary" disabled={!live||busy} onClick={apply}>Apply to all strategies <ArrowRight size={16}/></button>{!live&&<p className="caption">Saved replay mode. Start the local model service to change assumptions.</p>}<p className="caption">Common response delay {scenario.parameters.actuator_delay_seconds} s · minimum on/off {scenario.parameters.minimum_on_seconds}/{scenario.parameters.minimum_off_seconds} s · maximum four active zones.</p></details></Card></>}
  </>;
}

function Results({evidence,index}:{evidence:Evidence;index:ScenarioIndex}){
  const [caseId,setCaseId]=useState('east');const item=index.scenarios.find(s=>s.id===caseId)!;
  const warnings=(model:string)=>Object.values(evidence.test.descriptive_warnings_by_recording).reduce((a,r)=>{const m=r.models[model];return {matched:a.matched+m.matched_events,alerts:a.alerts+m.scored_warnings,events:a.events+m.scorable_events};},{matched:0,alerts:0,events:0});
  return <><PageTitle eyebrow="EVIDENCE, INCLUDING THE FAILURES" title="A result you can inspect." description="Measured forecasting errors and simulated control outcomes have different meanings. Both are shown with their baselines and limitations."/>
  <Card><Tag>Measured · held-out group 4</Tag><h2>The AI improves on persistence. The mean wins on MAE.</h2><p>Selection used group 3 validation only. The selected model was then evaluated on {number(evidence.test.samples,0)} windows across three group-4 recordings, with no test-driven retraining.</p><div className="table-wrap"><table><thead><tr><th>Predictor</th><th>MAE · µg/m³</th><th>RMSE · µg/m³</th><th>Mean signed error</th></tr></thead><tbody>{Object.entries(evidence.test.models).map(([name,m])=><tr key={name} className={name==='selected_model'?'selected-row':''}><td>{modelNames[name]}</td><td>{number(m.mae_ug_m3,3)}</td><td>{number(m.rmse_ug_m3,3)}</td><td>{number(m.mean_error_ug_m3,3)}</td></tr>)}</tbody></table></div><p>The model’s MAE is {number(evidence.test.mae_improvement_over_persistence_percent,2)}% below persistence, but {number((evidence.test.models.selected_model.mae_ug_m3/evidence.test.models.trailing_mean.mae_ug_m3-1)*100,2)}% above the trailing mean. This is prediction error, not pollution reduction.</p></Card>
  <div className="grid two"><Card><h3>Where the model fails</h3><div className="table-wrap"><table><thead><tr><th>Test recording</th><th>Model MAE</th><th>Mean MAE</th></tr></thead><tbody>{Object.entries(evidence.test.by_recording).map(([name,models])=><tr key={name}><td>{name.replace('lab_e4_drill','Drilling label · ')} s</td><td>{number(models.selected_model.mae_ug_m3)}</td><td>{number(models.trailing_mean.mae_ug_m3)}</td></tr>)}</tbody></table></div><p>Abrupt rises, peaks and the ten-second-label recording are weaknesses. Overlapping windows are correlated; thousands of windows do not mean thousands of independent experiments.</p></Card><Card><h3>Warning timing is limited</h3><div className="table-wrap"><table><thead><tr><th>Predictor</th><th>Matched runs</th><th>False alerts</th></tr></thead><tbody>{['selected_model','trailing_mean'].map(name=>{const w=warnings(name);return <tr key={name}><td>{modelNames[name]}</td><td>{w.matched}/{w.events}</td><td>{w.alerts-w.matched}</td></tr>;})}</tbody></table></div><p>Illustrative setting: 500 µg/m³, five consecutive snapshots, 60-second cooldown and a 30-second matching window. The 18 crossings are correlated within three records. Only one of three first onsets receives advance learned warning.</p><p className="caption">Not a regulatory limit or reliable warning-rate estimate.</p></Card></div>
  <Card><h3>Complete recorded test traces</h3><img className="evidence-plot" src="/reports/evaluation/test-full-profiles.png" alt="Recorded test PM10, trained model and baseline predictions across the three held-out recordings" loading="lazy"/><a className="source-link" href="/demo/documents/model-card.md" download>Download model card <Download size={14}/></a></Card>
  <Card><div className="section-heading"><div><Tag tone="sand">Simulation · same eight-minute window</Tag><h2>Water and exposure are a tradeoff.</h2></div><label className="field">Case<select aria-label="Results scenario" value={caseId} onChange={e=>setCaseId(e.target.value)}>{index.scenarios.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label></div><ResultTable scenario={{runs:Object.fromEntries(strategies.map(s=>[s,{metrics:item.metrics[s]}]))} as Scenario}/><p>Continuous spraying has the lowest mean concentration and the highest water use in these cases. Predictive uses less water than continuous, and more than reactive in the higher-risk cases. No single strategy wins every metric.</p><p className="caption">Water = commanded active time × assumed flow. Concentrations and effectiveness are uncalibrated simulation outputs. The 250 µg/m³ setting is a demo choice.</p><a className="source-link" href="/demo/documents/simulation.md" download>Download assumptions and all cases <Download size={14}/></a></Card>
  <Banner>Scope: one laboratory setup, group-based holdout, no independent outdoor site evaluation, no calibrated misting trial. A field pilot needs new measurements, calibration and a new untouched evaluation set.</Banner>
  <div className="attribution"><SourceLink href="https://data.mendeley.com/datasets/7f22n9v7hp/1">Askarov & Choi · 2024 · CC BY 4.0</SourceLink><SourceLink href="https://github.com/arifshekhk8/DustTwin-AI">Source, hashes and repeatable checks</SourceLink></div>
  </>;
}

function System({site}:{site:Site}){return <><PageTitle eyebrow="PROPOSED ROUND 2 DESIGN" title="From prototype to a calibrated pilot." description="The architecture is planned. No sensors, pumps, circuits or site hardware have been built or purchased for Round 1." action={<Tag tone="sand">Hardware deferred</Tag>}/>
  <Card><h3>One control loop, four boundary zones</h3><div className="architecture">{[['Sense','PM monitor + wind + reference checks'],['Forecast','Causal history → model + baseline'],['Decide','Boundary risk + minimum switch time'],['Act & log','Valve command + measured flow + audit log']].map(([title,text],i)=><div key={title}><span className="step">0{i+1}</span><h3>{title}</h3><p>{text}</p>{i<3&&<ArrowRight size={20}/>}</div>)}</div><SiteMap illustration/><p>Zone A = north, B = east, C = south, D = west. Wind direction means where the wind comes from. An eastward plume uses wind from 270°.</p></Card>
  <div className="grid three"><Card><h3>Calibrate before using</h3><p>Compare sensors with a reference monitor, characterize humidity and saturation, measure nozzle flow and coverage, and record independent construction events. A candidate sensor is not interchangeable with the training OPC-N3.</p></Card><Card><h3>Keep a safe manual path</h3><p>Use isolation, a suitable power supply, pressure-rated fittings, physical emergency stop and manual override. Validate missing-data fallback and real actuator limits with the team before deployment.</p></Card><Card><h3>Evaluate new evidence</h3><p>Log wind, source and boundary readings with commands and litres. Predeclare controller comparisons and reserve new sites/events for evaluation. Measure the contribution above background separately.</p></Card></div>
  <Card><h3>Prototype cost basis</h3>{site.costs?<><p>{site.costs.basis} · listings checked {site.costs.checked_date}. These are component listings, not quotations or a complete installed-system cost.</p><div className="table-wrap"><table><thead><tr><th>Proposed item</th><th>Qty</th><th>Listed unit price</th><th>Basis / dependency</th></tr></thead><tbody>{site.costs.items.map(item=><tr key={item.name}><td>{item.source_url?<SourceLink href={item.source_url}>{item.name}</SourceLink>:item.name}</td><td>{item.quantity}</td><td>{item.unit_price===null?'Quote needed':`${item.currency} ${number(item.unit_price,2)}`}</td><td>{item.note}</td></tr>)}</tbody></table></div><div className="button-row">{Object.entries(site.costs.currencies).map(([currency,total])=><Tag key={currency} tone="sand">Listed subtotal · {currency} {number(total,2)}</Tag>)}</div><p className="caption">{site.costs.exclusions.join(' · ')}</p></>:<p>Supplier evidence is being added to the final presentation packet. Unpriced parts will remain explicit.</p>}<a href="/demo/documents/feasibility.md" download className="source-link">Download feasibility notes <Download size={14}/></a></Card>
  </>;}
function Team({site}:{site:Site}){return <><PageTitle eyebrow={`${site.team.theme.toUpperCase()} · SOFTWARE PROTOTYPE`} title={`Meet ${site.team.name}.`} description="Our Round 1 prototype demonstrates measured-data forecasting, an inspectable control simulation and a working offline interface."/><div className="grid two team-grid">{site.team.members.map((member,i)=><Card key={member}><div className="member-number">0{i+1}</div><h2>{member}</h2><p>Team {site.team.name}</p></Card>)}</div><Card><dl className="key-values"><dt>Team name</dt><dd>{site.team.name}</dd><dt>Team ID</dt><dd>{site.team.team_id??site.team.team_id_status}</dd><dt>Theme</dt><dd>{site.team.theme}</dd><dt>Current scope</dt><dd>Round 1 software · hardware planned for Round 2</dd><dt>Evidence build parent</dt><dd className="mono break">{site.build_parent_commit}</dd></dl><SourceLink href="https://github.com/arifshekhk8/DustTwin-AI">Public source and progress</SourceLink></Card></>;}

const slides=[
  {time:'0:00–0:45',title:'DustTwin',kicker:'CTRL_V · THEME 2',body:'Forecast dust. Control the edge.',notes:'A software prototype for construction-site dust monitoring and selective misting. Hardware is deferred to Round 2.',page:'overview',cta:'Open the prototype'},
  {time:'0:45–1:45',title:'The problem at the boundary',kicker:'WHY WE BUILT THIS',body:'Construction activity creates a changing dust plume.',notes:'We propose watching the monitored signal, identifying exposed boundaries and making control decisions visible. Local context: World Bank reporting on Bangladesh air quality.',page:'overview',cta:'Show the idea'},
  {time:'1:45–2:45',title:'Real data, a frozen task',kicker:'MEASURED FORECASTING',body:'12 laboratory records. 120 seconds of history. A 30-second endpoint.',notes:'Raw OPC-N3 PM10, one-second causal grid, strict freshness. Groups 1/2 train, 3 select, 4 test. CC BY 4.0 attribution. One laboratory setup does not establish field accuracy.',page:'replay',cta:'Inspect a recording'},
  {time:'2:45–4:15',title:'Watch inference happen',kicker:'LIVE LOCAL DEMONSTRATION',body:'Past in. Forecast out. Actual revealed later.',notes:'Play and pause the measured replay. Inspect the 121 inputs and model hash. Compare the model with persistence and trailing mean. Seek forward to reveal an earlier forecast’s actual target.',page:'replay',cta:'Run the AI replay'},
  {time:'4:15–5:15',title:'The result is mixed',kicker:'HELD-OUT EVIDENCE',body:'Model MAE 88.405. Persistence 95.702. Trailing mean 81.565.',notes:'µg/m³ across 15,065 correlated test windows. Model improves on persistence but loses to the mean on MAE. Only one of three first onsets gets advance learned warning. Show failures.',page:'results',cta:'Show full results'},
  {time:'5:15–6:45',title:'One site, four strategies',kicker:'SIMULATION DEMONSTRATION',body:'Compare no control, continuous, reactive and predictive.',notes:'Play the diagonal case: A and B are exposed. Show water, commands and the common eight-minute comparison. Wind shift and sensor loss are included. Transport and mist response are assumptions.',page:'experiment',cta:'Run the site experiment'},
  {time:'6:45–7:45',title:'Show the tradeoff',kicker:'FAIR COMPARISON',body:'Less water than continuous. More than reactive in higher-risk cases.',notes:'Every strategy uses the same source, weather, actuator limits and assumed flow. Results come from traces. Continuous has the lowest mean concentration. We do not claim field suppression.',page:'results',cta:'Compare the evidence'},
  {time:'7:45–9:00',title:'What Round 2 must prove',kicker:'PROPOSED PILOT',body:'Calibration. Flow. Independent events. Outdoor validation.',notes:'Proposed source and boundary monitors, wind, isolated valves and a manual override. Show cost sources and quote gaps. The lower-cost sensor differs from OPC-N3 and needs new validation.',page:'system',cta:'Show the proposed design'},
  {time:'9:00–10:00',title:'A working, inspectable prototype',kicker:'CTRL_V',body:'The model runs. The evidence is visible. The demo works offline.',notes:'Round 1 delivers software, a frozen artifact, honest baselines and reproducible strategy traces. Ask for feedback on the pilot design. No hardware or qualification claims.',page:'team',cta:'Meet the team'},
];
function Present(){const [slide,setSlide]=useState(0);useEffect(()=>{const listener=(e:KeyboardEvent)=>{if((e.target as HTMLElement).matches('input,select,textarea'))return;if(e.key==='ArrowRight')setSlide(s=>Math.min(slides.length-1,s+1));if(e.key==='ArrowLeft')setSlide(s=>Math.max(0,s-1));};window.addEventListener('keydown',listener);return()=>window.removeEventListener('keydown',listener);},[]);const s=slides[slide];return <><PageTitle eyebrow="TEN-MINUTE JUDGE STORY" title="Ready to present." description="Use the slides to tell the story and open the working prototype for the two demonstrations. Arrow keys move between slides." action={<a className="button compact" href="/demo/documents/dusttwin-judge-packet.pdf" download><Download size={16}/>Evidence packet</a>}/><Card className="presentation-slide"><div className="slide-top"><span>{s.kicker}</span><Tag tone="sand">{s.time}</Tag></div><h2>{s.title}</h2><div className="slide-message">{s.body}</div><p>{s.notes}</p><button className="button primary" onClick={()=>go(s.page)}>{s.cta}<ArrowUpRight size={17}/></button><div className="slide-bottom"><span>{String(slide+1).padStart(2,'0')} / {slides.length}</span><div className="button-row"><button className="icon-button" aria-label="Previous slide" disabled={!slide} onClick={()=>setSlide(s=>s-1)}><ChevronLeft/></button><button className="icon-button" aria-label="Next slide" disabled={slide===slides.length-1} onClick={()=>setSlide(s=>s+1)}><ChevronRight/></button></div></div></Card><div className="slide-dots">{slides.map((s,i)=><button key={s.title} aria-label={`Slide ${i+1}: ${s.title}`} className={i===slide?'active':''} onClick={()=>setSlide(i)}>{i+1}</button>)}</div><div className="grid two"><Card><BookOpen size={22}/><h3>Judge notes and evidence</h3><p>Read the script, model card and simulation assumptions. All assets are local; external sources are optional reference links.</p><div className="document-links">{[['judge-script.md','Ten-minute script'],['model-card.md','Model card'],['simulation.md','Simulation evidence'],['feasibility.md','Pilot and costs'],['offline-demo.md','Offline instructions']].map(([file,name])=><a href={`/demo/documents/${file}`} key={file} download>{name}<Download size={14}/></a>)}</div></Card><Card><ShieldCheck size={22}/><h3>Presentation modes</h3><p><strong>Live local:</strong> the Python service executes the fitted model on your Mac.</p><p><strong>Saved replay:</strong> the standalone fallback shows previously computed predictions and strategy traces. It does not execute AI or change assumptions.</p><p>Practice the spoken pitch with the team. A software rehearsal cannot verify a human presentation.</p></Card></div></>;}

export default function App(){
  const [page,setPage]=useState(location.hash.slice(1)||'overview'),[mobile,setMobile]=useState(false),[site,setSite]=useState<Site|null>(null),[evidence,setEvidence]=useState<Evidence|null>(null),[replay,setReplay]=useState<ReplayIndex|null>(null),[scenarios,setScenarios]=useState<ScenarioIndex|null>(null),[live,setLive]=useState(false),[error,setError]=useState('');
  useEffect(()=>{const update=()=>{setPage(location.hash.slice(1)||'overview');setMobile(false);window.scrollTo(0,0);};window.addEventListener('hashchange',update);return()=>window.removeEventListener('hashchange',update);},[]);
  useEffect(()=>{const c=new AbortController();Promise.all([getJson<Site>('/demo/site.json',c.signal),getJson<Evidence>('/demo/evidence.json',c.signal),fallbackJson<ReplayIndex>('/v1/replay','/demo/replay/index.json',c.signal),fallbackJson<ScenarioIndex>('/v1/scenarios','/demo/simulation/index.json',c.signal)]).then(([s,e,r,i])=>{setSite(s);setEvidence(e);setReplay(r);setScenarios(i);}).catch(e=>{if(!c.signal.aborted)setError(String(e));});getJson<{ready:boolean}>('/health',c.signal).then(h=>{if(!c.signal.aborted)setLive(h.ready);}).catch(()=>{});return()=>c.abort();},[]);
  const ready=site&&evidence&&replay&&scenarios;const current=pages.find(p=>p[0]===page)??pages[0];
  return <div className="app-shell"><aside className={`sidebar ${mobile?'open':''}`}><a href="#overview" className="brand"><div className="brand-mark"><Wind size={23}/></div><span>DustTwin<small>INTELLIGENT SITE CONTROL</small></span></a><div className="nav-label">WORKSPACE</div><nav>{pages.map(([key,label,Icon])=><a href={`#${key}`} key={key} className={current[0]===key?'active':''} aria-current={current[0]===key?'page':undefined}><Icon size={18}/>{label}{key==='present'&&<span className="nav-arrow"><ArrowUpRight size={14}/></span>}</a>)}</nav><div className="sidebar-bottom"><div className="prototype-label"><span className="status-dot"/><strong>Software prototype</strong></div><p>Measured forecast +<br/>simulated site control</p><a href="https://github.com/arifshekhk8/DustTwin-AI" target="_blank" rel="noreferrer">View repository <ArrowUpRight size={14}/></a></div></aside>{mobile&&<button className="nav-overlay" aria-label="Close navigation" onClick={()=>setMobile(false)}/>}
    <div className="main-shell"><header className="topbar"><div className="breadcrumb"><button className="icon-button mobile-menu" aria-label={mobile?'Close menu':'Open menu'} onClick={()=>setMobile(!mobile)}>{mobile?<X size={19}/>:<Menu size={19}/>}</button><span>DustTwin</span><span className="slash">/</span><strong>{current[1]}</strong></div><div className="topbar-right"><Tag tone={live?'mint':'sand'}>{live?'Local model ready':'Saved replay mode'}</Tag><span className="team-badge">CTRL_V <span>ROUND 1</span></span></div></header><main>{error?<Banner tone="sand">The local evidence could not be loaded: {error}. Use the included local server; this website cannot run directly from a file URL.</Banner>:!ready?<div className="loading">Loading local evidence…</div>:current[0]==='overview'?<Overview evidence={evidence} site={site}/>:current[0]==='replay'?<Replay index={replay}/>:current[0]==='experiment'?<Experiment index={scenarios} live={live}/>:current[0]==='results'?<Results evidence={evidence} index={scenarios}/>:current[0]==='system'?<System site={site}/>:current[0]==='team'?<Team site={site}/>:<Present/>}</main><footer className="app-footer"><span>DustTwin · CTRL_V · Theme 2</span><span>Round 1 software · Hardware proposed for Round 2</span></footer></div></div>;
}
