import { useEffect, useState } from 'react';
import { Play, Pause, RotateCcw, ArrowUpRight, Wind, Droplets } from 'lucide-react';
import { clock, number } from './data';
export function Tag({children,tone='mint'}:{children:React.ReactNode;tone?:string}) {return <span className={`tag ${tone}`}><i/>{children}</span>;}
export function PageTitle({eyebrow,title,description,action}:{eyebrow:string;title:string;description:string;action?:React.ReactNode}){return <header className="page-title"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{description}</p></div>{action}</header>;}
export function Card({children,className=''}:{children:React.ReactNode;className?:string}){return <section className={`card ${className}`}>{children}</section>;}
export function MetricCard({label,value,unit,note,tone=''}:{label:string;value:string;unit?:string;note:string;tone?:string}){return <Card className={`metric ${tone}`}><span className="small-label">{label}</span><div className="metric-value">{value}<small>{unit}</small></div><p>{note}</p></Card>;}
export function usePlayback(initial:number,min:number,max:number){const [second,setSecond]=useState(initial),[playing,setPlaying]=useState(false),[speed,setSpeed]=useState(5);useEffect(()=>{if(!playing)return;const timer=setInterval(()=>setSecond(old=>{const next=Math.min(max,old+speed);if(next===max)setPlaying(false);return next;}),1000);return()=>clearInterval(timer);},[playing,speed,max]);return {second,setSecond,playing,setPlaying,speed,setSpeed,min,max,reset:()=>{setPlaying(false);setSecond(initial);}};}
export type Playback=ReturnType<typeof usePlayback>;
export function Transport({player,label}:{player:Playback;label:string}){return <div className="transport"><div className="transport-buttons"><button className="button primary compact" onClick={()=>player.setPlaying(!player.playing)} aria-label={player.playing?'Pause replay':'Play replay'}>{player.playing?<Pause size={16}/>:<Play size={16}/>} {player.playing?'Pause':'Play'}</button><button className="icon-button" aria-label="Reset replay" onClick={player.reset}><RotateCcw size={17}/></button><label className="speed">Speed <select aria-label="Playback speed" value={player.speed} onChange={e=>player.setSpeed(Number(e.target.value))}>{[1,2,5,10,20].map(s=><option key={s} value={s}>{s}×</option>)}</select></label></div><div className="timeline"><input type="range" aria-label={label} min={player.min} max={player.max} step={1} value={player.second} onChange={e=>{player.setPlaying(false);player.setSecond(Number(e.target.value));}}/><span className="mono">{clock(player.second)} / {clock(player.max)}</span></div></div>;}
export type Series={name:string;color:string;points:{x:number;y:number}[];dashed?:boolean};
export function LineChart({series,setting,height=245,xLabel='Recorded elapsed time',xMax}:{series:Series[];setting?:number;height?:number;xLabel?:string;xMax?:number}){
  const points=series.flatMap(s=>s.points), width=850,left=56,right=22,top=22,bottom=40;
  const minX=points.length?Math.min(...points.map(p=>p.x)):0,maxX=xMax??(points.length?Math.max(...points.map(p=>p.x)):1);
  const maxY=Math.max(100,setting??0,...points.map(p=>p.y))*1.13;
  const x=(n:number)=>left+(n-minX)/Math.max(1,maxX-minX)*(width-left-right),y=(n:number)=>height-bottom-n/maxY*(height-top-bottom);
  return <div className="chart"><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label={series.map(s=>s.name).join(', ')}><title>{series.map(s=>s.name).join(' versus ')} in µg/m³</title>{[0,.25,.5,.75,1].map(p=><g key={p}><line x1={left} x2={width-right} y1={y(p*maxY)} y2={y(p*maxY)} className="chart-grid"/><text x={left-10} y={y(p*maxY)+4} textAnchor="end">{Math.round(p*maxY)}</text></g>)}{setting!==undefined&&<g><line x1={left} x2={width-right} y1={y(setting)} y2={y(setting)} stroke="#bd8e58" strokeDasharray="5 5"/><text x={width-right} y={y(setting)-7} textAnchor="end" fill="#bd8e58">Demo setting {setting}</text></g>}{series.map(s=><g key={s.name}><polyline points={s.points.map(p=>`${x(p.x)},${y(p.y)}`).join(' ')} fill="none" stroke={s.color} strokeWidth={1.8} strokeDasharray={s.dashed?'4 4':undefined}/>{s.points.length===1&&<circle cx={x(s.points[0].x)} cy={y(s.points[0].y)} r={5} fill={s.color}/>}</g>)}{[0,.25,.5,.75,1].map(p=><text key={p} x={x(minX+p*(maxX-minX))} y={height-15} textAnchor="middle">{clock(minX+p*(maxX-minX))}</text>)}</svg><div className="chart-footer"><span>{xLabel} · PM10 µg/m³</span><div className="legend">{series.map(s=><span key={s.name}><i style={{background:s.color}}/>{s.name}</span>)}</div></div></div>;
}
export function SiteMap({windFrom=270,concentrations=[40,40,40,40],active=[false,false,false,false],risk=[],illustration=false}:{windFrom?:number;concentrations?:number[];active?:boolean[];risk?:string[];illustration?:boolean}){
  const ids=['A','B','C','D'],names=['NORTH','EAST','SOUTH','WEST'],positions=[[300,38],[552,185],[300,337],[48,185]];
  return <div className="site-map"><svg viewBox="0 0 600 380" role="img" aria-label="Site map: A north, B east, C south, D west"><defs><pattern id="mapGrid" width="24" height="24" patternUnits="userSpaceOnUse"><path d="M24 0H0V24" fill="none" stroke="#233139" strokeWidth=".6"/></pattern><radialGradient id="dustGlow"><stop stopColor="#d6a367" stopOpacity=".42"/><stop offset="1" stopColor="#d6a367" stopOpacity="0"/></radialGradient></defs><rect width="600" height="380" fill="url(#mapGrid)"/><rect x="100" y="77" width="400" height="217" rx="13" fill="#111d23" stroke="#42535d" strokeDasharray="5 5"/><g transform={`rotate(${(windFrom+180)%360-90} 300 185)`}><ellipse cx="380" cy="185" rx="160" ry="65" fill="url(#dustGlow)"/><path d="M292 185C337 144 430 151 496 174M293 186C360 201 439 211 503 196M302 183C374 167 421 176 475 181" className="dust-path" fill="none" stroke="#bf955f" strokeOpacity=".55" strokeDasharray="3 7"/><path d="M390 182h46m-9-7 9 7-9 7" stroke="#d1ac75" fill="none"/></g><g transform="translate(253 144)"><path d="M0 20L46 0L92 20L46 40Z" fill="#7f7058"/><path d="M0 20V68L46 88V40Z" fill="#4d4b42"/><path d="M46 40L92 20V68L46 88Z" fill="#656253"/><path d="M10 36L36 47M10 49L36 60M57 50L80 40M57 64L80 54" stroke="#968779" strokeWidth="4"/><circle cx="46" cy="46" r="8" fill="#e4b278"/></g><text x="300" y="260" textAnchor="middle" className="map-label">SOURCE MONITOR / CONSTRUCTION</text>{positions.map(([px,py],i)=><g key={ids[i]}><line x1={i===1||i===3?(i===1?496:104):px} y1={i===0?80:i===2?292:py} x2={px} y2={py} stroke={active[i]?'#78d9b2':'#3e5059'} strokeWidth={active[i]?3:1}/><rect x={px-37} y={py-22} width="74" height="44" rx="8" fill={active[i]?'#1a4134':risk.includes(ids[i])?'#3e3020':'#16232b'} stroke={active[i]?'#78d9b2':risk.includes(ids[i])?'#c99e63':'#45555e'}/><text x={px} y={py-4} textAnchor="middle" fill={active[i]?'#9ff2cb':'#edf0ef'} fontSize="13" fontWeight="700">{ids[i]} · {names[i]}</text><text x={px} y={py+12} textAnchor="middle" fill="#b9c8cd" fontSize="11">{illustration?'ZONE':`${number(concentrations[i],0)} µg/m³`}</text>{active[i]&&<circle cx={px} cy={py} r="34" className="mist-ring"/>}</g>)}<text x="107" y="320" className="map-label">120 × 80 m ASSUMED SITE</text><text x="493" y="320" textAnchor="end" className="map-label">N ↑</text></svg><div className="map-footer"><span><Wind size={14}/>Wind from {number(windFrom,0)}° → travels {number((windFrom+180)%360,0)}°</span><span><Droplets size={14}/>Mint = zone command</span></div></div>;
}
export function SourceLink({href,children}:{href:string;children:React.ReactNode}){return <a href={href} target="_blank" rel="noreferrer" className="source-link">{children}<ArrowUpRight size={13}/></a>;}
